
package de.dpunkt.myaktion.monitor.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpendeDelegatorService", targetNamespace = "http://ws.monitor.myaktion.dpunkt.de/", wsdlLocation = "http://localhost:9080/my-aktion-monitor/SpendeDelegatorService?wsdl")
public class SpendeDelegatorService
    extends Service
{

    private final static URL SPENDEDELEGATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SPENDEDELEGATORSERVICE_EXCEPTION;
    private final static QName SPENDEDELEGATORSERVICE_QNAME = new QName("http://ws.monitor.myaktion.dpunkt.de/", "SpendeDelegatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/my-aktion-monitor/SpendeDelegatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPENDEDELEGATORSERVICE_WSDL_LOCATION = url;
        SPENDEDELEGATORSERVICE_EXCEPTION = e;
    }

    public SpendeDelegatorService() {
        super(__getWsdlLocation(), SPENDEDELEGATORSERVICE_QNAME);
    }

    public SpendeDelegatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPENDEDELEGATORSERVICE_QNAME, features);
    }

    public SpendeDelegatorService(URL wsdlLocation) {
        super(wsdlLocation, SPENDEDELEGATORSERVICE_QNAME);
    }

    public SpendeDelegatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPENDEDELEGATORSERVICE_QNAME, features);
    }

    public SpendeDelegatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpendeDelegatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpendeDelegator
     */
    @WebEndpoint(name = "SpendeDelegatorPort")
    public SpendeDelegator getSpendeDelegatorPort() {
        return super.getPort(new QName("http://ws.monitor.myaktion.dpunkt.de/", "SpendeDelegatorPort"), SpendeDelegator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpendeDelegator
     */
    @WebEndpoint(name = "SpendeDelegatorPort")
    public SpendeDelegator getSpendeDelegatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.monitor.myaktion.dpunkt.de/", "SpendeDelegatorPort"), SpendeDelegator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPENDEDELEGATORSERVICE_EXCEPTION!= null) {
            throw SPENDEDELEGATORSERVICE_EXCEPTION;
        }
        return SPENDEDELEGATORSERVICE_WSDL_LOCATION;
    }

}
